name: Build and Push to Docker Hub

on:
  push:
    branches: ["main"]
  workflow_run:
    workflows: ["CI/CD Tests & Coverage & SonarCloud"]
    types:
      - completed

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    # Se déclenche seulement si les tests précédents ont réussi
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
