name: Tests & Coverage
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-frontend:
    name: Frontend Tests & Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: front/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build frontend
        run: npm run build --if-present
      - name: Run tests with coverage
        run: npm run test -- --code-coverage --watch=false --browsers=ChromeHeadless
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: front/coverage
          retention-days: 1

  test-backend:
    name: Backend Tests & Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run tests with coverage
        run: mvn test jacoco:report
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: back/target/site/jacoco
          retention-days: 1
