name: SonarCloud Analysis
on:
  workflow_run:
    workflows: ["Tests & Coverage"]
    types: [completed]
    branches: [main]
  pull_request:
    branches: ["main"]
  workflow_dispatch: # Pour tests manuels

jobs:
  sonar-frontend:
    name: SonarCloud Frontend
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # TOUJOURS faire les tests (comme le backend)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: front/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build --if-present

      - name: Run tests with coverage
        run: npm run test -- --code-coverage --watch=false --browsers=ChromeHeadless

      # Debug optionnel (tu peux l'enlever plus tard)
      - name: Debug coverage files
        run: |
          echo "=== Coverage directory content ==="
          ls -la coverage/ || echo "No coverage directory"
          echo "=== LCOV file exists? ==="
          test -f coverage/lcov.info && echo "✅ lcov.info found" || echo "❌ lcov.info NOT found"

      - name: SonarCloud Scan Frontend
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: front
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  sonar-backend:
    name: SonarCloud Backend
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    defaults:
      run:
        working-directory: back

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests with coverage
        run: mvn test jacoco:report

      - name: SonarCloud Scan Backend
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: back
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
