name: SonarCloud Analysis
on:
  workflow_run:
    workflows: ["Tests & Coverage"]
    types: [completed]
    branches: [main]

  pull_request:
    branches: ["main"]

jobs:
  sonar-frontend:
    name: SonarCloud Frontend
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'pull_request' }}
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Download des artifacts de coverage du workflow précédent
      - name: Download frontend coverage
        if: github.event_name != 'pull_request'
        uses: actions/download-artifact@v4
        with:
          name: frontend-coverage
          path: front/coverage
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      # Pour les PR, on refait les tests
      - name: Setup Node.js (for PR)

        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: front/package-lock.json

      - name: Install and test (for PR)
        run: |
          npm ci
          npm run test -- --code-coverage --watch=false --browsers=ChromeHeadless

      - name: SonarCloud Scan Frontend
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: front
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  sonar-backend:
    name: SonarQube Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests with coverage
        run: mvn test jacoco:report

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: back/target/site/jacoco

      - name: SonarQube Scan Backend
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: back
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
